from pydantic import BaseModel, ConfigDict, Field
from typing import Literal
from datetime import datetime, timezone
import uuid


# ── Incoming alarm from SNS / CloudWatch ──────────────────────────────────────

class AlarmDimension(BaseModel):
    name: str
    value: str


class AlarmTrigger(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    metric_name: str = Field(alias="MetricName")
    namespace: str = Field(alias="Namespace")
    statistic: str = Field(alias="Statistic")
    dimensions: list[AlarmDimension] = Field(alias="Dimensions")
    period: int = Field(alias="Period")
    threshold: float = Field(alias="Threshold")
    comparison_operator: str = Field(alias="ComparisonOperator")


class AlarmPayload(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    alarm_name: str = Field(alias="AlarmName")
    alarm_description: str = Field(default="No description", alias="AlarmDescription")
    aws_account_id: str = Field(alias="AWSAccountId")
    new_state_value: str = Field(alias="NewStateValue")
    new_state_reason: str = Field(alias="NewStateReason")
    state_change_time: str = Field(alias="StateChangeTime")
    region: str = Field(alias="Region")
    trigger: AlarmTrigger = Field(alias="Trigger")


# ── Alarm types AlarmBrain can classify ───────────────────────────────────────

AlarmType = Literal[
    "lambda_throttle",
    "rds_cpu_high",
    "sqs_depth_high",
    "ec2_autoscaling",
    "alb_5xx",
    "unknown"
]


# ── Outgoing incident brief generated by Claude ───────────────────────────────

class IncidentBrief(BaseModel):
    incident_id: str = Field(default_factory=lambda: f"INC-{uuid.uuid4().hex[:8].upper()}")
    generated_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    alarm_name: str
    alarm_type: AlarmType
    severity: Literal["P1", "P2", "P3", "P4"]
    probable_cause: str
    affected_services: list[str]
    immediate_actions: list[str]
    healthcare_impact: str
    escalate_if: str
    runbook_reference: str


# ── SNS wrapper — what Lambda actually receives ───────────────────────────────

class SNSMessage(BaseModel):
    Message: str        # CloudWatch alarm JSON as a string — needs json.loads()
    Subject: str = ""
    Timestamp: str = ""
    TopicArn: str = ""


class SNSRecord(BaseModel):
    Sns: SNSMessage


class SNSEvent(BaseModel):
    Records: list[SNSRecord]